/*
 * This source file was generated by the Gradle 'init' task
 */
package com.piyushchoukse.sampletestagentdemo

class Calculator {
    fun add(first: Int, second: Int): Int = Math.addExact(first, second)
}

class CalculatorUiModel(private val calculator: Calculator) {
    fun renderAddition(first: Int, second: Int): String = "$first + $second = ${calculator.add(first, second)}"
}

fun main() {
    println(CalculatorUiModel(Calculator()).renderAddition(2, 2))
}
