/*
 * This source file was generated by the Gradle 'init' task
 */
package com.piyushchoukse.sampletestagentdemo

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Test
import java.io.ByteArrayOutputStream
import java.io.PrintStream

class AppTest {
    @Test
    fun add_returnsFour_forTwoPlusTwo() {
        val calculator = Calculator()

        val result = calculator.add(2, 2)

        assertEquals(4, result)
    }

    @Test
    fun add_supportsNegativeValues() {
        val calculator = Calculator()

        val result = calculator.add(-5, 3)

        assertEquals(-2, result)
    }

    @Test
    fun add_throwsArithmeticException_onOverflow() {
        val calculator = Calculator()

        assertThrows(ArithmeticException::class.java) {
            calculator.add(Int.MAX_VALUE, 1)
        }
    }

    @Test
    fun renderAddition_showsUiOutput_forTwoPlusTwo() {
        val uiModel = CalculatorUiModel(Calculator())

        val uiText = uiModel.renderAddition(2, 2)

        assertEquals("2 + 2 = 4", uiText)
    }

    @Test
    fun main_printsExpectedEquation() {
        val originalOut = System.out
        val capturedOut = ByteArrayOutputStream()
        System.setOut(PrintStream(capturedOut))
        try {
            main()
        } finally {
            System.setOut(originalOut)
        }

        assertEquals("2 + 2 = 4", capturedOut.toString().trim())
    }
}
